#!/bin/bash

cd $(dirname "$0")

function submodule {
  dir=".hg-submodules/$1"
  url="$2"
  rev="$3"

  if [[ -d "$dir" ]]; then
    hg -R "$dir" pull
  else
    hg clone "$url" "$dir"
  fi

  if [[ "$rev" == "" ]]; then
    rev=tip
  fi

  hg -R "$dir" up "$rev"
}

submodule qimportbz http://hg.mozilla.org/users/robarnold_cmu.edu/qimportbz
submodule hg-prompt-sjl https://jlebar@bitbucket.org/sjl/hg-prompt
submodule hg-paste https://jlebar@bitbucket.org/sjl/hg-paste
submodule hg-patience http://hg.mozilla.org/users/jlebar_mozilla.com/hg-patience
submodule bzexport http://hg.mozilla.org/users/tmielczarek_mozilla.com/bzexport
submodule mqext https://bitbucket.org/sfink/mqext
submodule qbackout https://bitbucket.org/sfink/qbackout
submodule t https://jlebar@bitbucket.org/sjl/t
submodule search_plugin https://jlebar@bitbucket.org/jlebar/search_plugin
