# TODO: Set CONFDIR automatically.  dirname $0 is insufficient.
export CONFDIR="$HOME/conf"

# Make sure that our path is right.
. $CONFDIR/shell-src/set-path.sh

export EDITOR=vim
export CCACHE_BASEDIR=$HOME
export CCACHE_HARDLINK=1
export CCACHE_SLOPPINESS="file_stat_matches,time_macros"
export ANDROID_SDK=$HOME/code/moz/android-sdk-linux_x86
export ANDROID_NDK=$HOME/code/moz/android-ndk-r6

set -o vi
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

RUN_T="python $CONFDIR/t/t.py"
alias t="$RUN_T -t $HOME/tasks --list tasks"
alias mozt="$RUN_T -t $HOME/tasks --list mozilla"

# On mac, use pbcopy
alias xclip="xclip -selection c"

# rse function
if [ -f $CONFDIR/shell-src/funcs.sh ]; then
    . $CONFDIR/shell-src/funcs.sh
fi

# hg completion
if [ -f $CONFDIR/shell-src/bash-completion-hg ]; then
    . $CONFDIR/shell-src/bash-completion-hg
fi

# Call our not-checked-in machine-specific bashrc, if it exists.
if [ -f $HOME/.bashrc_machine ]; then
  . $HOME/.bashrc_machine
fi

# machine-specific bashrc
if [[ -f $CONFDIR/machines/$MACHINE/bashrc ]]; then
  . $CONFDIR/machines/$MACHINE/bashrc
fi

vcs_branchname() {
  if [[ "$USE_QTOP_PROMPT" == "" ]]; then
    return
  fi

  qtop=`hg prompt '{patch|topindex}{ {patch}}' 2>/dev/null`
  if [[ "$qtop" != "" ]]; then
    echo " ($qtop)"
    return
  fi

  git_branch=`git branchname`
  if [[ "$git_branch" != "" ]]; then
    echo " ($git_branch)"
    return
  fi
}

PROMPT_COMMAND='MERCURIAL_QTOP=`vcs_branchname`'
PS1='\[\033[$PROMPT_COLOR\]\u@\h\[\033[00m\]:\[\033[$PROMPT_COLOR\]\w\[\033[00m\]$MERCURIAL_QTOP\$ '

shopt -s histappend
# force ignoredups and ignorespace
export HISTCONTROL='ignoreboth'

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# enable color support of ls and also add handy aliases
if [ -x "$(which dircolors)" ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

# Bash configuration for shared history.
# (From https://news.ycombinator.com/item?id=3537392)
#
# Append to ~/.bash_history instead of overwriting it -- this stops terminals
# from overwriting one another's histories.
shopt -s histappend
# Only load the last 1000 lines from your ~/.bash_history -- if you need an
# older entry, just grep that file.
HISTSIZE=10000
# Don't truncate ~/.bash_history -- keep all your history, ever.
unset HISTFILESIZE
# Add a timestamp to each history entry.
HISTTIMEFORMAT="%Y/%m/%d %H:%M:%S  "
# Don't remember trivial 1- and 2-letter commands.
HISTIGNORE=?:??
# What it says.
HISTCONTROL=ignoredups
# Save each history entry immediately (protects against terminal crashes/
# disconnections, and interleaves commands from multiple terminals in correct
# chronological order).
PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

PERL_MB_OPT="--install_base \"/usr/local/google/home/jlebar/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/usr/local/google/home/jlebar/perl5"; export PERL_MM_OPT;

export GOPATH="$HOME/.gocode"

# See http://wiki/twiki/bin/view/Main/G4Recipes#Diff_Tools
export P4DIFF=gitdiff
#export P4MERGE=meldmerge
export G4MULTIDIFF=1

export USE_QTOP_PROMPT=1

# Machine-specific stuff
if [[ "$PROMPT_COLOR" == "" ]]; then
  if [[ "$HOSTNAME" == jlebar.* ]] || [[ "$HOSTNAME" == jlebar.* ]]; then
    PROMPT_COLOR="31m"
  elif [[ "$HOSTNAME" == jlebar-macbookpro* ]]; then
    PROMPT_COLOR="32m"
  else
    PROMPT_COLOR="34m"
  fi
fi

alias g1="cd $HOME/overlay/google1/google3"
alias g2="cd $HOME/overlay/g2/google3"
alias g3="cd $HOME/overlay/g3/google3"
