#!/usr/bin/env python

import os, sys

def fatal(msg):
    print msg
    sys.exit(1)

if __name__ == '__main__':
    confdir = os.environ['CONFDIR']
    rcdir = os.path.join(confdir, 'rc')
    home = os.environ['HOME']

    for f in os.listdir(rcdir):
        src = os.path.join(rcdir, f)
        dst = os.path.join(home, '.' + f)

        # Don't link bashrc_machine into $HOME
        if f == 'bashrc_machine':
            continue

        # Don't link this file into $HOME.
        if os.path.samefile(src, sys.argv[0]):
            continue

        try:
            os.remove(dst)
        except:
            pass

        os.symlink(src, dst)
